#node webServer
version: '2'
services:
  web:
    image: node:11
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: bash -c "npm install && node server.js"
    ports:
      - "80:80"
    mem_limit: 1024m

#monitoring

#gui
  cadvisor:
    image: google/cadvisor:v0.29.0
    links:
      - influxdb:influxsrv
    command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxsrv:8086
    restart: on-failure
    ports:
      - "8888:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    mem_limit: 1024m

#db
  influxdbData:
    image: busybox
    volumes:
      - /var/lib/influxdb
      - ./data/influxdb:/data
 
  influxdb:
    image: tutum/influxdb:0.9
    restart: on-failure
    environment:
      - PRE_CREATE_DB=cadvisor
    ports:
      - "8083:8083"
      - "8086:8086"
    expose:
      - "8090"
      - "8099"
    volumes_from:
      - "influxdbData"
    mem_limit: 1024m
